### ISSUE TITLE
获取封面图API失效

### ISSUE THREAD

**Issue by MasterOfStar** [isecret/yuncun#3]
获取封面图API失效，返回的链接无法被拉取
包括网站上的也失效了

**Comment by MasterOfStar** [comment]
好像是网易云那边的问题
https:\/\/p2.music.126.net\/KK3YNRE9flpcZCYkDS8Z3g==\/109951163826159510.jpg
比如返回的这个链接，换成p1.music.126.net就没有问题。

**Comment by MasterOfStar** [comment]
反正我这边看是这样的
[![截图.bmp](https://i.loli.net/2019/05/31/5cf0d3726315f73759.bmp)](https://i.loli.net/2019/05/31/5cf0d3726315f73759.bmp)

**Comment by isecret** [comment]
封面是正常的啊，你所说的是背景吗？背景我已经换成了取图片主色作为纯色背景了。

**Comment by MasterOfStar** [comment]
> 封面是正常的啊，你所说的是背景吗？背景我已经换成了取图片主色作为纯色背景了。

可能是我太菜了。
新手写了个python调用拉取封面图的脚本，然后拉取图片一直connectionERROR。
然后一看网页和之前不一样，于是就想当然了XD
